//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMCLocker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locker()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public int locker_index { get; set; }
        public int locker_number { get; set; }
        public string state { get; set; }
        public string locker_type { get; set; }
        public Nullable<int> owned { get; set; }
        public Nullable<int> history_id { get; set; }
        public int id { get; set; }
        public string note { get; set; }
    
        public virtual history history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
