//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMCLocker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_ContractLiquite
    {
        public string StaffCode { get; set; }
        public Nullable<System.DateTime> LiquidationDate { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> Retiring { get; set; }
        public Nullable<int> NoAL { get; set; }
        public bool Infringe { get; set; }
    }
}
