//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMCLocker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_InputDataToManage
    {
        public string Staffcode { get; set; }
        public System.DateTime AppliedDate { get; set; }
        public int KindView { get; set; }
        public string Customer { get; set; }
        public string Job { get; set; }
        public string Direct_InDirect { get; set; }
        public string Stage { get; set; }
    }
}
