//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMCLocker
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string locker_number { get; set; }
        public string locker_index { get; set; }
        public string shoes_number { get; set; }
        public string shoes_index { get; set; }
        public string Sex { get; set; }
    }
}
